### ISSUE TITLE
Hitting back after oAuth takes you back to twitter

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#20]
Probably a tricky problem to solve but unfortunately this will come up for sure as the main oAuth trigger is the recipe page on which the only navigation action is to go back.

**Comment by stubailo** [comment]
Is there a reason we are using the "back" function of the browser instead of specifying the route?

**Comment by zol** [comment]
@stubailo - Yeah there is. When there are multiple pages that link to a sub page you either have to keep track of where the user came from yourself or use the browser's back mechanism.

**Comment by tmeasday** [comment]
Soln: We show a menu button (rather than back) if we are at the initial route. This happens in particular if you hit the recipe after oauth.

An alternative solution would be to have built-in fallback "back" routes for such situations but it's slightly more complex and arguably more surprising for users.

**Comment by zol** [comment]
Lgtm.
