### ISSUE TITLE
Include image in tweet

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#31]

**Comment by tmeasday** [comment]
Phew!

Ok we _could_ have used the `OAuth1Binding` to do this but for some reason it includes the form parameters in the oauth header (which isn't necessary, request doesn't do it), which makes the request blow up if one of those parameters is an image.

So possibly we could ask MDG to fix this.

Otherwise, I've included a pretty simple solution involving `Npm.require('request');`. I think we should head back upstream to find out what they want us to do.

**Comment by zol** [comment]
I'm going to refactor the existing code to use the npm request module as I think it's more correct.
