### ISSUE TITLE
iOS & Safari flickering

### ISSUE THREAD

**Issue by domyen** [percolatestudio/mdg-localmarket#4]
@zoltan in iphone & safari there is a flickering problem when transitioning from page to page, doesn't happen in chrome.

I tried to troubleshoot the css with various gpu accelerations to no avail. I suspect it might have something to do with momentum. Can you check it out?

**Comment by zol** [comment]
@tmeasday - seeing this too. I've a feeling this is iron-router related, any ideas off the bat? (I'm going to hold off looking at it till you've responded)

**Comment by zol** [comment]
Was looking at this a bit more as I realized the overlay is a simple plugin with no routing and the flickering is occurring there too. I can make the flicker disappear for the overlay if I give the `#email-overlay` div `display: hidden`. My theory is it's being drawn for a split second as it's placed into the dom then becoming hidden by velocity and slowly faded in.

The problem with the side-side transitions is probably similar but @tmeasday I'm curious what the ramifications of this might be as it's a more complex dom-reflow.

**Comment by tmeasday** [comment]
Are we using velocity wrong? I can't see why there'd be a reflow in between
inserting and starting velocity.

Haven't had a chance to look at this one yet as Sous was broken for me
yesterday.

**Comment by dgreensp** [comment]
I think velocity is expecting the element to start hidden.  Adding a `.hide()` before invoking velocity seems to help.

My first impression of the way animation is done is that there are two many layers of abstraction.

The zero-abstraction way actually looks pretty good in code, which you can achieve by removing the `{{#momentum}}` helper from `client/templates/body.html`, making all `div.page` have `position: absolute` by removing `[data-momentum] >` from `client/stylesheets/globals/layout.lessimport`, and adding this code to `client/templates/body.js`:

```
Template._body.rendered = function () {
  this.find("#content-container")._uihooks = {
    insertElement: function(node, next) {
      $(node)
        .hide()
        .insertBefore(next)
        .velocity("transition.slideLeftIn", { duration: 500 });
    },
    removeElement: function(node) {
      $(node)
        .velocity("transition.slideLeftOut", {
          duration: 500,
          complete: function() {
            $(node).remove();
          }
        });
    }
  };
};
```

It could be made even more transparent by using CSS transitions instead of Velocity.

**Comment by tmeasday** [comment]
Hi @dgreensp 

The thing is that the complexity in the momentum-iron-router package comes from solving two problems that are very common in practice:
1. Different transitions in different circumstances. 
   
   This is great for a right-to-left transition but when the user hits the back button, we need to go left-to-right. Plus if they hit a link in the menu, we need to not transition at all. [1]. We could write all that down above but i think it starts to get pretty complicated and an abstraction starts to sound sensible :)
2. Queuing transitions
   
   If an app uses a loading page (which we **don't** do in Sous, and in general we think isn't great UX), then it's very common when routing from A->B to actually need to transition from A->loading->B. Often the "loading->B" transition will trigger while the "A->loading" animation is in progress.
   
   If you do the naive thing it looks completely broken (lots of pages sliding around on top of each other). 
   
   Loading pages are _very_ common thanks to the pattern being codified in IR (my bad ;) ). We could just ignore it in Sous, but it seems to me that it's just going to be something people continually butt up against otherwise. Plus we still use it in Verso so we need to solve it anyway :)

[1] Plus in practice for real apps you often want to transition differently depending on the routes involved. For instance some pages want to slide up from the bottom, others fade in, etc, etc.

**Comment by zol** [comment]
Regarding velocity, are you guys completely against using it? In our
experience it's more strait forward to understand and work with especially
when you start building more complex animations (e.g an animating list).
Better performance is also easier to obtain than by hand rolling css.

**Comment by zol** [comment]
Closing this out, fixed in the latest momentum package.

**Comment by Slava** [comment]
We tried the webapp on iphones/ipads today, all side-by-side transitions are jumping from 0% to 100%, then back to 0% and then play the animation. Works great on desktop browsers, though.

**Comment by zol** [comment]
Thanks, we're in the process of removing momentum so I think this is a bug
introduced by that. We'll QA once we're done.

_Zoltan Olah_
Partner/Engineer
http://percolatestudio.com
+1 415 696 4455

**Comment by tmeasday** [comment]
@Slava I think maybe you were running off the master branch?

Cordova branch works pretty well, at least for me. I've merged master into it.

I'm not sure if we should bother backporting the various uihook changes to master? Perhaps we should just merge cordova into master? @zol do you have any specific plans here?

**Comment by zol** [comment]
Was planning on merging cordova to master. I guess I was holding off till
0.9.2 is out of the RC stage but if well all think merging cordova to
master is fine let's do it.

_Zoltan Olah_
Partner/Engineer
http://percolatestudio.com
+1 415 696 4455
